/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VSlugRouteImport } from './routes/v.$slug'
import { Route as ApiBadgeSlugRouteImport } from './routes/api/badge.$slug'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/v/$slug',
  path: '/v/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBadgeSlugRoute = ApiBadgeSlugRouteImport.update({
  id: '/api/badge/$slug',
  path: '/api/badge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/extension': typeof ExtensionRoute
  '/library': typeof LibraryRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/v/$slug': typeof VSlugRoute
  '/api/badge/$slug': typeof ApiBadgeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/extension': typeof ExtensionRoute
  '/library': typeof LibraryRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/v/$slug': typeof VSlugRoute
  '/api/badge/$slug': typeof ApiBadgeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/extension': typeof ExtensionRoute
  '/library': typeof LibraryRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/v/$slug': typeof VSlugRoute
  '/api/badge/$slug': typeof ApiBadgeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/extension'
    | '/library'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/verify'
    | '/v/$slug'
    | '/api/badge/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/extension'
    | '/library'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/verify'
    | '/v/$slug'
    | '/api/badge/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/extension'
    | '/library'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/verify'
    | '/v/$slug'
    | '/api/badge/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExtensionRoute: typeof ExtensionRoute
  LibraryRoute: typeof LibraryRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  VSlugRoute: typeof VSlugRoute
  ApiBadgeSlugRoute: typeof ApiBadgeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/v/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/badge/$slug': {
      id: '/api/badge/$slug'
      path: '/api/badge/$slug'
      fullPath: '/api/badge/$slug'
      preLoaderRoute: typeof ApiBadgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExtensionRoute: ExtensionRoute,
  LibraryRoute: LibraryRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  VSlugRoute: VSlugRoute,
  ApiBadgeSlugRoute: ApiBadgeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
